= Templates

Tittle templates are a way to templatize your configuration files. Tittle supports
a very simple syntax to allow for substitution of variables in a configuration file
that is machine and user dependent.

== Syntax

Variables in template files are surrounded by double braces `{{...}}`, and should only
contain alphanumeric characters. To provide a value for a variable, run `tittle edit me`
and add an entry into the *vars* map.

== Example

Let's say you have a configuration file for your terminal under `~/.term.yml` that has
the following contents:
```yml
font:
  normal:
    family: Terminus
    style: Medium

  size: 10.0
```
Now, say you want the value of `size` to depend on the user/machine. You would first
create a template file `~/.term.yml.template` (note: this filename is arbitrary) with
the contents
```yml
font:
  normal:
    family: Terminus
    style: Medium

  size: {{terminal_font_size}}
```
Note how the variables in the file are surrounded with double braces `{{...}}`, this
is required in order for variable substitution to be applied.

Now, we need to track this template and specify where it should render to, after
variable substitution:
```
tittle track ~/.term.yml.template --name terminal --renders_to ~/.term.yml
```
See <<commands#, commands>>, and <<tracking#, tracking>> for information on the
*--name* argument. Lastly, we must specify the value of the `terminal_font_size`
variable by editing the overrides specific to this user/machine:
```
tittle edit me
```
This will open up this user/machine's overrides with `$EDITOR` (see the *edit* command
in <<commands#, commands>> for details). We then need to add `terminal_font_size` to
the *vars* field:
```
{
  "dest": {},
  "templates": {},
  "vars": {
    "terminal_font_size": "10.0"
  }
}
```
To specify the value on a different user/machine, run `tittle edit me` from that
user/machine. Lastly, to render the template to its location, do
```
tittle render
```
which renders all templates. Tittle will inform you if a template references a variable
that is not defined for this user/machine.
